# Site settings
name: Blair MacIntyre
title: Blair MacIntyre
author: Blair MacIntyre
simple_search: http://google.com/search
email: blair@macmynatt.com
description: > # this means to ignore newlines until "baseurl:"
  Professor, Designer, Husband, Father
baseurl: ""
url: "https://blairmacintyre.me"
disqusURL: "http://blairmacintyre.me"
twitter_username: blairmacintyre
github_username:  blairmacintyre
permalink:    /:year/:month/:day/:title/
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

exclude: ['Rakefile', 'README.md']

# Build settings
markdown: kramdown
kramdown:  
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

gems: ['jekyll-paginate', 'jekyll/scholar']

git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Sites/blairmacintyre.me/
  
  
# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /project/:path/
  articles:
    output: true
    permalink: /articles/:path/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
  -
    scope:
      path: ""
      type: "articles"
    values:
      comments: true

# scholar stuff at https://github.com/inukshuk/jekyll-scholar
scholar:
  style: apa
  locale: en

  sort_by: year, month
  order: descending, ascending

  group_by: year, type
  group_order: descending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"