# Site settings
name: Blair MacIntyre
title: Blair MacIntyre
author: Blair MacIntyre
simple_search: http://google.com/search
email: blair@macmynatt.com
description: > # this means to ignore newlines until "baseurl:"
  Professor, Designer, Husband, Father
baseurl: ""
url: "https://blairmacintyre.me"
disqusURL: "http://blairmacintyre.me"
twitter_username: blairmacintyre
github_username:  blairmacintyre
permalink:    /:year/:month/:day/:title/
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
plugins_dir:     ./_plugins

editor: code

exclude: ['Rakefile', 'README.md', "node_modules", "package.json", "vendor"]

post:
    template: _templates/post-template
    extension: "md"
    
page:
    template: _templates/page-template
    extension: "md"

micro:
    template: _templates/micro-template
    extension: "md"

# Build settings
markdown: kramdown
kramdown:  
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

git:
  branch: site-source-master
  
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ../blairmacintyre.me.master/
  
# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /project/:path/
  articles:
    output: true
    permalink: /articles/:path/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
  -
    scope:
      path: ""
      type: "articles"
    values:
      comments: true

# scholar stuff at https://github.com/inukshuk/jekyll-scholar
scholar:
  style: apa
  locale: en

  sort_by: year, month
  order: descending, ascending

  group_by: year, type
  group_order: descending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

prose:
# not sure if I want to restrict:  may want to include _articles and _portfolio as well
#  rooturl: '_posts'
  siteurl: 'https://blairmacintyre.me/'
  relativeLinks: 'https://blairmacintyre.me/links.jsonp'
  media: 'assets'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "multiselect"
          label: "Select Categories"
          alterable: "true"
          options:
            - name: "WebAR"
              value: "webar"
            - name: "Commercial"
              value: commercial
            - name: "Argon"
              value: "argon"
            - name: "Mozilla"
              value: "mozilla"
            - name: "WebXR"
              value: "webxr"
            - name: "Education"
              value: "education"
            - name: "Research"
              value: "research"
            - name: "Art"
              value: "art"
            - name: "Personal"
              value: "personal"
            - name: "Musings"
              value: "musings"
            - name: "Conference"
              value: "conference"
            - name: "Privacy"
              value: "privacy"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "hidden"
          value: "blair"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: "CURRENT_DATETIME"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: "true"
          options:
            - name: "Micropost"
              value: "micropost"
            - name: "Metaverse"
              value: "metaverse"
            - name: "Argon4"
              value: "argon4"
            - name: "argon.js"
              value: "argonjs"
            - name: "Open Source"
              value: "open source"
    _articles:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
    _portfolio:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
