---
title: Blair MacIntyre
timezone: US/Eastern
collections:
  articles:
    title: Articles
    output: true
    permalink: "/articles/:path/"
  portfolio:
    title: Portfolio
    output: true
    permalink: "/project/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
    permalink: "/assets/uploads/:path"
defaults:
- scope:
    path: ''
    type: posts
  values:
    comments: true
    layout: post
- scope:
    path: ''
    type: articles
  values:
    comments: true
name: Blair MacIntyre
author: Blair MacIntyre
simple_search: http://google.com/search
email: blair@macmynatt.com
description: Professor, Designer, Husband, Father
baseurl: ''
url: https://blairmacintyre.me
disqusURL: http://blairmacintyre.me
twitter_username: blairmacintyre
github_username: blairmacintyre
permalink: "/:year/:month/:day/:title/"
markdown_ext: markdown,mkdown,mkdn,mkd,md
plugins_dir: "./_plugins"
editor: code
exclude:
- Rakefile
- README.md
- node_modules
- package.json
- vendor
post:
  template: _templates/post-template
  extension: md
page:
  template: _templates/page-template
  extension: md
micro:
  template: _templates/micro-template
  extension: md
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
git:
  branch: site-source-master
transfer:
  command: rsync
  settings: "-av"
  source: _site/
  destination: "../blairmacintyre.me.master/"
paginate: 15
paginate_path: "/blog/page:num/"
scholar:
  style: apa
  locale: en
  sort_by: year, month
  order: descending, ascending
  group_by: year, type
  group_order: descending
  source: "./_bibliography"
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  replace_strings: true
  join_strings: true
  use_raw_bibtex_entry: true
  bibtex_filters:
  - superscript
  - latex
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"
