# Site settings
name: Blair MacIntyre
title: Blair MacIntyre
email: blair@macmynatt.com
description: > # this means to ignore newlines until "baseurl:"
  Professor, Designer, Husband, Father
baseurl: ""
url: "https://blairmacintyre.me"
disqusURL: "http://blairmacintyre.me"
twitter_username: blairmacintyre
github_username:  blairmacintyre

permalink:    /:year/:month/:day/:title/

# Build settings
markdown: kramdown

highlighter: pygments

gems: [jekyll-paginate]

# Pagination
paginate: 15
paginate_path: "/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  articles:
    output: true
    permalink: /articles/:path/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
  -
    scope:
      path: ""
      type: "articles"
    values:
      comments: true
